---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: /ansiblefiles/ngnixconf/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
      become: yes
	  remote_src: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
