---
- name: This is a hello-world example
  hosts: 172.19.158.169
  tasks:
    - name: Create a file called '/tmp/testfile123.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile123.txt
