---
- name: This is a hello-world example
  hosts: all
  tasks:
    - name: Create a file called '/tmp/testfile123.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile123.txt
        
        
        
        MIIEpAIBAAKCAQEAquHm5PkoWSuFKQHe0Cl9pWBaQLYPuwGvm2P1Ttr8wrYHDWmr
z5WLqMF4vKUOV5X6224G+iuJbbewUf5ilD9Ng5eVt5MSWv4oO1vO2wgpIxPos2qH
tv0R7UKllQcqaN1ibnk5Vl9IwlFtQuLNYZOnkjlkhnvDrkimVxot2iTwQZNNKjz/
rJOExaufdBjD61PHnfEPVqzKjnYjvkVSntzetO0R+devItZfXFr/0KySL5A5DB4v
rdAZw215a/wO6zuOyTfMdihBxuH7VdwVBIIhzzs2N8vdFNq27Anpicdjvd1Nzj7H
zezn2rRYJGj45fUtI4OknkG8iS3x5HUYiDfR8QIDAQABAoIBAFxY0qfhQn3V+BNu
MFR8Z6tsw7l+6kdcpOMsBNDFpZ0wM+V6ut/m6F+dlrsT1AlfQv88mcauqolBoKbe
+7Uz9Jbt33oin+POwD074zEZWunbA4GaS5eHch2vS76a7b9YDK65ElRsD+z7hjmE
Sgu2ePOb0oie7+QK3OHrguYF2lUE/LSRmgpKYohLol3OBT9WZy+8ydM06YDgV874
gOyVY6GC6h7r+JkORgMR+ctZcTxEbmd6/Y/oOHy4IAo9c+grTQ0ObL4bMzZKPpDu
/k/YNaGbiAxp/YhcjJwq4sOOS4vua2AQ1EKAfp6IM6xkCSYpo0TQCD//QyPgMqmW
cbl7lEUCgYEA09vm5WJ2bLmBRY2ARQS125/kbWXhm5LRSLS8rYKF9JwN/yXFKyCQ
z4ADb7anhi781ZNJM1DljaNs+Mi4fJM29ijfQznNMMvotiR4mpJuyeMEPrAcTqxy
1b31iwUtCGMxOBNVxxAeCbw2SD/A6xwjrPM8Sbai8qdfHjTXddcj0+8CgYEAznxm
M+DEa4kAfPJs5voFEjxQHi+Dr0FtAX79Pkg74SnylcSRNuYKGGfRHNxRgJDWgSTu
iXyGy7ngw+3ps+oGgpPugBTAxYWg2zvjFv6SqgdeqMW13BCRiSZzRLBElFbkYgM/
iUHnlHMOWWnwUTJh8CZPFODJM9a5hYeFNZNpWB8CgYAQAhW4T3BTVtEFyGNg07JK
HhLMkV4yuy1FKSL4mVw113TXSqtTTuqiQzH/RvXxlatVGAP39Kzjvu2E/uWxxA3r
G7uDAOMYRNAYszjJtTbZ2mV/tx7scutaazgagRGeCKC3c/6PRBCA+8++NdMF8OJh
Nx/fEgXOAAeX6LY/GTqD0QKBgQChI2N+yMGASgIff/CMsECU4oyDggD6G8y9hiSL
HkPci6fMSQIqHYtzUFFYfHb+Jgm/7tpYYN2wzvYg8OGYjeFWtatCOO/XNVk6vZmS
sEg0eFveyawKeMOajG8YA5cBTG4eLvq+WrgmmUNxc8MfGnpjtwGwAVwDIGbXVdMW
5FspcQKBgQCgqvMoBogUs0y6Rctf8S2BF+WUi/YokhM3OnV+yEaFbbmbK+QCfll/
eE1k+aIcrvItqKgXZNnM2fHi5RB44n2i28lWB//C0wwZlNbnraR5E4EUDOLmFC2h
ecw17LuvXQLAayOn+XU/FWraEwG5nSpEbiPlO24p9KhFbcKZD/RGGw==
